services:
  database:
    image: 'postgres:latest'
    container_name: postgres-spring
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=mypassword'
    ports:
      - "5432:5432"
    volumes:
       - ./init/schema.sql:/docker-entrypoint-initdb.d/init.sql