version: '1'

services:
  db:
    image: 'docker-spring-boot-postgres:latest'
    container_name: my_postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data